services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:5000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
    restart: unless-stopped
  db:
    # ref https://stackoverflow.com/questions/76877963/setting-up-postgresql-database-server-in-docker-container-for-express-api
    image: postgres:latest
    restart: unless-stopped
    environment:
      # defined in .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    # todo remove when deploying
    ports:
      - "5432:5432"

